In [1]:
import pandas as pd
import numpy as np

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import cross_val_score,StratifiedKFold,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,precision_score,f1_score,recall_score

In [4]:
!pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\krish\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (1.26.4)
Collecting pandas>=1.2 (from seaborn)
  Downloading pandas-2.3.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.3-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.2-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.58.4-cp311-cp311-win_amd64.whl.metadata (108 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.8-cp311-cp311-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\krish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-11.2.1-cp311-cp311-win_amd64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\krish\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.2->seaborn)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.2->seaborn)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\krish\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.3-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 3.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.1 MB 3.6 MB/s eta 0:00:02
   --------- ------------------------------ 1.8/8.1 MB 3.2 MB/s eta 0:00:02
   ------------- -------------------------- 2.6/8.1 MB 3.1 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.1 MB 2.9 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.1 MB 3.0 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.1 MB 3.1 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 3.2 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.1 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 3.1 MB/s eta 0:00:00
Downloading contourpy-1.3.2-cp311-cp311-win_amd64.whl (222 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.58.4-cp311-cp311-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ------------- -------------------------- 0.8/2.2 MB 2.4 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.2 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 2.1/2.2 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 2.8 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp311-cp311-win_amd64.whl (71 kB)
Downloading pandas-2.3.0-cp311-cp311-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.1 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.1 MB 3.0 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.1 MB 3.3 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/11.1 MB 3.7 MB/s eta 0:00:03
   ---------------- ----------------------- 4.5/11.1 MB 3.6 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.1 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/11.1 MB 4.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.1 MB 4.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.1 MB 4.1 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.1 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 4.1 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --------------- ------------------------ 1.0/2.7 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.7 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  2.6/2.7 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 3.9 MB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, pandas, matplotlib, seaborn

   ----------------------------------------  0/11 [pytz]
   ----------------------------------------  0/11 [pytz]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   --- ------------------------------------  1/11 [tzdata]
   ------- --------------------------------  2/11 [pyparsing]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   ---------- -----------------------------  3/11 [pillow]
   -------------- -------------------------  4/11 [kiwisolver]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   ----------------------------- ----------  8/11 [pandas]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   -------------------------------- -------  9/11 [matplotlib]
   ------------------------------------ --- 10/11 [seaborn]
   ------------------------------------ --- 10/11 [seaborn]
   ------------------------------------ --- 10/11 [seaborn]
   ---------------------------------------- 11/11 [seaborn]

Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.58.4 kiwisolver-1.4.8 matplotlib-3.10.3 pandas-2.3.0 pillow-11.2.1 pyparsing-3.2.3 pytz-2025.2 seaborn-0.13.2 tzdata-2025.2

In [5]:
import seaborn as sns
sns.set()

In [27]:
n_estimators = [int(x) for x in np.linspace(start=200,stop=2000,num=10)]
max_features = ['sqrt']
max_depth = [int(x) for x in np.linspace(10,110,num=11)]
min_samples_split = [2,5,8,10,15,20]
min_samples_leaf = [1,2,4,6,8,10]
bootstrap = [True,False]

random_parms = {
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'min_samples_split':min_samples_split,
    'min_samples_leaf':min_samples_leaf,
    'bootstrap':bootstrap
                }

In [8]:
data = pd.read_csv('data/final_df.csv')

In [9]:
data.columns

Index(['season', 'round', 'weather_warm', 'weather_cold', 'weather_dry',
       'weather_wet', 'weather_cloudy', 'driver', 'grid', 'podium',
       'driver_points', 'driver_wins', 'driver_standings_pos',
       'constructor_points', 'constructor_wins', 'constructor_standings_pos',
       'qualifying_time', 'driver_age', 'circuit_id_adelaide',
       'circuit_id_albert_park', 'circuit_id_americas', 'circuit_id_bahrain',
       'circuit_id_brands_hatch', 'circuit_id_catalunya', 'circuit_id_detroit',
       'circuit_id_estoril', 'circuit_id_galvez', 'circuit_id_hockenheimring',
       'circuit_id_hungaroring', 'circuit_id_imola', 'circuit_id_indianapolis',
       'circuit_id_interlagos', 'circuit_id_istanbul',
       'circuit_id_jacarepagua', 'circuit_id_jerez', 'circuit_id_kyalami',
       'circuit_id_magny_cours', 'circuit_id_marina_bay', 'circuit_id_monaco',
       'circuit_id_monza', 'circuit_id_nurburgring', 'circuit_id_phoenix',
       'circuit_id_red_bull_ring', 'circuit_id_ricard', 'circuit_id_rodriguez',
       'circuit_id_sepang', 'circuit_id_shanghai', 'circuit_id_silverstone',
       'circuit_id_sochi', 'circuit_id_spa', 'circuit_id_suzuka',
       'circuit_id_valencia', 'circuit_id_villeneuve', 'circuit_id_yas_marina',
       'circuit_id_yeongam', 'circuit_id_zandvoort', 'nationality_American',
       'nationality_Australian', 'nationality_Austrian', 'nationality_Belgian',
       'nationality_Brazilian', 'nationality_British', 'nationality_Canadian',
       'nationality_Danish', 'nationality_Dutch', 'nationality_Finnish',
       'nationality_French', 'nationality_German', 'nationality_Italian',
       'nationality_Japanese', 'nationality_Mexican', 'nationality_Russian',
       'nationality_Spanish', 'nationality_Swedish', 'constructor_alfa',
       'constructor_arrows', 'constructor_bar', 'constructor_benetton',
       'constructor_brabham', 'constructor_ferrari', 'constructor_footwork',
       'constructor_force_india', 'constructor_haas', 'constructor_jaguar',
       'constructor_jordan', 'constructor_larrousse', 'constructor_ligier',
       'constructor_lotus_f1', 'constructor_mclaren', 'constructor_mercedes',
       'constructor_minardi', 'constructor_prost', 'constructor_red_bull',
       'constructor_renault', 'constructor_sauber', 'constructor_team_lotus',
       'constructor_toro_rosso', 'constructor_toyota', 'constructor_tyrrell',
       'constructor_williams'],
      dtype='object')

In [10]:
data.drop(['podium','qualifying_time'],axis = 1)
X= data.copy()

In [13]:
rf = RandomForestClassifier(n_estimators=1600,min_samples_split=8,min_samples_leaf=4,max_features='auto',max_depth=70,bootstrap=True)
kf = StratifiedKFold(n_splits=10,random_state=None,shuffle=False)
#for train_index,test_index in kf.split(X,y):
#     X_train,X_test = X.iloc[train_index],X.iloc[test_index]
#     y_train,y_test = y.iloc[train_index],y.iloc[test_index]

In [12]:
# rf_rand = RandomForestClassifier()
# rf_random = RandomizedSearchCV(estimator=rf_rand,param_distributions=random_parms,n_iter=10,cv=10,verbose=2,n_jobs=-1 )
# rf_random.fit(X,y)
# rf_random.best_params_

In [14]:
X = data.copy()

sc  = StandardScaler()
le = LabelEncoder()
X['driver'] = le.fit_transform(X['driver'])

X_train = X[(X['season'] < 2024) ].drop('grid',axis = 1)
y_train = X[X['season'] < 2024]['grid']

In [15]:
X_2024 = X[(X['season'] == 2024) & (X['round'] < 4)].drop('grid',axis = 1)
y_2024 = X[(X['season'] == 2024) & (X['round'] < 4)]['grid']

X_train = pd.concat([X_train,X_2024])
y_train = pd.concat([y_train,y_2024])

In [16]:
X_train

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,podium,driver_points,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
0,1983,1,False,False,True,False,False,109,15,0,...,0,0,0,0,0,0,0,0,0,1
1,1983,1,False,False,True,False,False,176,6,0,...,0,0,0,1,0,0,0,0,0,0
2,1983,1,False,False,True,False,False,212,4,0,...,0,0,0,0,0,0,0,0,0,0
3,1983,1,False,False,True,False,False,171,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1983,1,False,False,True,False,False,223,7,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15013,2023,4,True,False,False,False,True,193,16,0,...,0,0,0,0,0,0,0,0,0,1
15014,2023,4,True,False,False,False,True,233,19,0,...,0,0,0,0,0,0,0,0,0,0
15015,2023,4,True,False,False,False,True,110,13,1,...,0,0,0,0,0,0,0,0,0,0
15016,2023,4,True,False,False,False,True,79,14,4,...,0,0,0,0,0,0,0,0,0,0
15017,2023,4,True,False,False,False,True,58,20,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
y_train

0         1
1         2
2         3
3         4
4         5
         ..
15013    14
15014    15
15015    16
15016    17
15017    18
Name: grid, Length: 15018, dtype: int64

In [20]:
X_test = X[(X['season'] == 2023) & (X['round'] == 4)].drop('grid',axis = 1)
y_test = X[(X['season'] == 2023) & (X['round'] == 4)]['grid']

In [21]:
X_test

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,podium,driver_points,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
15000,2023,4,True,False,False,False,True,126,3,0,...,0,0,0,0,0,0,0,0,0,0
15001,2023,4,True,False,False,False,True,139,2,44,...,0,0,1,0,0,0,0,0,0,0
15002,2023,4,True,False,False,False,True,166,1,18,...,0,0,1,0,0,0,0,0,0,0
15003,2023,4,True,False,False,False,True,189,5,20,...,0,0,0,0,0,0,0,0,0,0
15004,2023,4,True,False,False,False,True,93,6,20,...,0,0,0,0,0,0,0,0,0,0
15005,2023,4,True,False,False,False,True,8,4,30,...,0,0,0,0,0,0,0,0,0,0
15006,2023,4,True,False,False,False,True,159,9,0,...,0,0,0,0,0,0,0,0,0,0
15007,2023,4,True,False,False,False,True,216,10,0,...,0,0,0,0,0,0,0,0,0,0
15008,2023,4,True,False,False,False,True,206,7,8,...,0,0,0,0,0,0,0,0,0,0
15009,2023,4,True,False,False,False,True,168,11,0,...,0,0,0,0,0,0,0,0,0,0
15010,2023,4,True,False,False,False,True,188,8,18,...,0,0,0,0,0,0,0,0,0,0
15011,2023,4,True,False,False,False,True,3,12,1,...,0,0,0,0,0,0,0,0,0,1
15012,2023,4,True,False,False,False,True,30,18,4,...,0,0,0,0,0,0,0,0,0,0
15013,2023,4,True,False,False,False,True,193,16,0,...,0,0,0,0,0,0,0,0,0,1
15014,2023,4,True,False,False,False,True,233,19,0,...,0,0,0,0,0,0,0,0,0,0
15015,2023,4,True,False,False,False,True,110,13,1,...,0,0,0,0,0,0,0,0,0,0
15016,2023,4,True,False,False,False,True,79,14,4,...,0,0,0,0,0,0,0,0,0,0
15017,2023,4,True,False,False,False,True,58,20,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
y_test

15000     1
15001     2
15002     3
15003     4
15004     5
15005     6
15006     7
15007     8
15008     9
15009    10
15010    11
15011    12
15012    13
15013    14
15014    15
15015    16
15016    17
15017    18
Name: grid, dtype: int64

In [30]:
rf = RandomForestClassifier(max_features='sqrt')  
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

In [31]:
y_pred_rf

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [32]:
import pickle

filename = 'rf_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(rf, file)

In [33]:
X_later = X_test.copy()
X_later = X_later[['season','round','driver']]

X_later['pred_pos'] = y_pred_rf
X_later['actual'] = y_test

In [34]:
X_later = X_later.sort_values(by = 'pred_pos')

In [35]:
X_later.shape

(18, 5)

In [37]:
X_later['pred_pos'] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

In [38]:
X_later['driver'] = le.inverse_transform(X_later['driver'])

In [39]:
X_later

       season  round           driver  pred_pos  actual
15000    2023      4          leclerc         1       1
15001    2023      4   max_verstappen         2       2
15002    2023      4            perez         3       3
15003    2023      4            sainz         4       4
15004    2023      4         hamilton         5       5
15005    2023      4           alonso         6       6
15006    2023      4           norris         7       7
15007    2023      4          tsunoda         8       8
15008    2023      4           stroll         9       9
15009    2023      4          piastri        10      10
15010    2023      4          russell        11      11
15011    2023      4            albon        12      12
15012    2023      4           bottas        13      13
15013    2023      4         sargeant        14      14
15014    2023      4             zhou        15      15
15015    2023      4  kevin_magnussen        16      16
15016    2023      4            gasly        17      17
15017    2023      4         de_vries        18      18

In [41]:
X.dtypes

season                    int64
round                     int64
weather_warm               bool
weather_cold               bool
weather_dry                bool
                          ...
constructor_team_lotus    int64
constructor_toro_rosso    int64
constructor_toyota        int64
constructor_tyrrell       int64
constructor_williams      int64
Length: 100, dtype: object

In [44]:
svc = SVC()
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
svc.fit(X_train,y_train)
y_pred_svc = svc.predict(X_test)
cnf_mat_svc = confusion_matrix(y_test,y_pred)
cnf_mat_svc = cnf_mat_svc/cnf_mat_svc.sum()

In [45]:
X_later = X_test.copy()
X_later = X_later[['season','round','driver',]]

X_later['pred_pos'] = y_pred_rf
X_later['actual'] = y_test

X_later = X_later.sort_values(by = 'pred_pos')

In [46]:
X_later.shape

(18, 5)

In [47]:
X_later

       season  round  driver  pred_pos  actual
15000    2023      4     126         1       1
15001    2023      4     139         2       2
15002    2023      4     166         3       3
15003    2023      4     189         4       4
15004    2023      4      93         5       5
15005    2023      4       8         6       6
15006    2023      4     159         7       7
15007    2023      4     216         8       8
15008    2023      4     206         9       9
15009    2023      4     168        10      10
15010    2023      4     188        11      11
15011    2023      4       3        12      12
15012    2023      4      30        13      13
15013    2023      4     193        14      14
15014    2023      4     233        15      15
15015    2023      4     110        16      16
15016    2023      4      79        17      17
15017    2023      4      58        18      18

In [48]:
X_later['driver'] = le.inverse_transform(X_later['driver'])

In [49]:
X_later['pred_pos'] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

In [50]:
X_later

       season  round           driver  pred_pos  actual
15000    2023      4          leclerc         1       1
15001    2023      4   max_verstappen         2       2
15002    2023      4            perez         3       3
15003    2023      4            sainz         4       4
15004    2023      4         hamilton         5       5
15005    2023      4           alonso         6       6
15006    2023      4           norris         7       7
15007    2023      4          tsunoda         8       8
15008    2023      4           stroll         9       9
15009    2023      4          piastri        10      10
15010    2023      4          russell        11      11
15011    2023      4            albon        12      12
15012    2023      4           bottas        13      13
15013    2023      4         sargeant        14      14
15014    2023      4             zhou        15      15
15015    2023      4  kevin_magnussen        16      16
15016    2023      4            gasly        17      17
15017    2023      4         de_vries        18      18

In [51]:
y_pred_svc

array([13,  7,  7, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13])

In [52]:
rf_pression = precision_score(y_test, y_pred_rf, average = 'micro' )
rf_f1 = f1_score(y_test,y_pred_rf,average='macro')
rf_recall = recall_score(y_test,y_pred_rf,average='macro')
svc_pression = precision_score(y_test, y_pred_svc, average='micro')
svc_f1 = f1_score(y_test,y_pred_svc,average='macro')
svc_recall = recall_score(y_test,y_pred_svc,average='macro')
metrics_dict ={
    'RandomForestClassifier':{'precision_score':rf_pression,'f1_score':rf_f1,'recall_score':rf_recall},
    'SVC':{'precision_score':svc_pression,'f1_score':svc_f1,'recall_score':svc_recall}
}
metrics_df = pd.DataFrame(metrics_dict)
metrics_df

                 RandomForestClassifier       SVC
precision_score                     1.0  0.055556
f1_score                            1.0  0.006536
recall_score                        1.0  0.055556